"""
Seeding logic and demo data for the Insurance Underwriting POC.
"""

from .connection import get_db, _ensure_data_dir
from .schema import DDL

_SEED_CASES = [
    {
        "app_no": "OS121345678",
        "name": "Kailash Suresh",
        "first_name": "KAILASH",
        "last_name": "SURESH",
        "dob": "15/03/1985",
        "age": 41,
        "gender": "Male",
        "marital_status": "Single",
        "nationality": "Indian",
        "resident_status": "NRI",
        "pan_no": "ABCKS1234K",
        "aadhaar_no": "1234 5678 9012",
        "mobile": "+91-9886122211",
        "email": "kailash.suresh@email.com",
        "address1": "NO 10 11TH STREET TANSI NAGAR",
        "address2": "",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600017",
        "country": "Sweden",
        "occupation": "Salaried",
        "organisation_type": "PRIVATE LTD",
        "industry": "IT/Software",
        "education": "Graduate",
        "annual_income": 6000000,
        "experian_income": 300000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "12345678901234",
        "bank_name": "HDFC Bank",
        "ifsc": "HDFC0001234",
        "nominee_name": "Priya Suresh",
        "nominee_relation": "Wife",
        "plan": "UW3 - Term Life Insurance",
        "product_code": "UW3",
        "sum_assured": 4500000,
        "premium": 50000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "FR",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 4500000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS234567890",
        "name": "David Mathew",
        "first_name": "DAVID",
        "last_name": "MATHEW",
        "dob": "22/07/1980",
        "age": 44,
        "gender": "Male",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "BCDMX5678Y",
        "aadhaar_no": "2345 6789 0123",
        "mobile": "+91-9876543210",
        "email": "david.mathew@email.com",
        "address1": "12 MG ROAD",
        "address2": "",
        "city": "Bangalore",
        "state": "Karnataka",
        "pincode": "560001",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "PUBLIC LTD",
        "industry": "Banking/Finance",
        "education": "Post Graduate",
        "annual_income": 8000000,
        "experian_income": 500000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "98765432101234",
        "bank_name": "ICICI Bank",
        "ifsc": "ICIC0000123",
        "nominee_name": "Mary Mathew",
        "nominee_relation": "Wife",
        "plan": "UW8 - Whole Life",
        "product_code": "UW8",
        "sum_assured": 3000000,
        "premium": 50000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "FR",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 13240571,
        "audit_flag": "",
        "status": "In Progress",
    },
    {
        "app_no": "OS345678901",
        "name": "Sarah Johnson",
        "first_name": "SARAH",
        "last_name": "JOHNSON",
        "dob": "10/11/1990",
        "age": 34,
        "gender": "Female",
        "marital_status": "Single",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "CEFSY9012Z",
        "aadhaar_no": "3456 7890 1234",
        "mobile": "+91-9123456789",
        "email": "sarah.johnson@email.com",
        "address1": "45 PARK STREET",
        "address2": "",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pincode": "400001",
        "country": "India",
        "occupation": "Self Employed",
        "organisation_type": "PRIVATE LTD",
        "industry": "Healthcare",
        "education": "Graduate",
        "annual_income": 4000000,
        "experian_income": 200000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "11223344556677",
        "bank_name": "Axis Bank",
        "ifsc": "UTIB0000456",
        "nominee_name": " Robert Johnson",
        "nominee_relation": "Father",
        "plan": "E35 - Endowment",
        "product_code": "E35",
        "sum_assured": 2000000,
        "premium": 48000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "FR",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 2000000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS456789012",
        "name": "Rajesh Patel",
        "first_name": "RAJESH",
        "last_name": "PATEL",
        "dob": "05/06/1975",
        "age": 49,
        "gender": "Male",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "NRI",
        "pan_no": "DFGPR3456A",
        "aadhaar_no": "4567 8901 2345",
        "mobile": "+91-9034567890",
        "email": "rajesh.patel@email.com",
        "address1": "78 ASHRAM ROAD",
        "address2": "",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pincode": "380006",
        "country": "USA",
        "occupation": "Business",
        "organisation_type": "PRIVATE LTD",
        "industry": "Manufacturing",
        "education": "Graduate",
        "annual_income": 12000000,
        "experian_income": 700000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "55667788990011",
        "bank_name": "SBI",
        "ifsc": "SBIN0001234",
        "nominee_name": "Sunita Patel",
        "nominee_relation": "Wife",
        "plan": "UW3 - Term Life Insurance",
        "product_code": "UW3",
        "sum_assured": 5000000,
        "premium": 75000,
        "sourcing_type": "FR",
        "advisor_code": "R2640845",
        "holding_type": "FR",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 5000000,
        "audit_flag": "YES",
        "status": "Pending",
    },
    {
        "app_no": "OS567890123",
        "name": "Anita Sharma",
        "first_name": "ANITA",
        "last_name": "SHARMA",
        "dob": "14/02/1982",
        "age": 42,
        "gender": "Female",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "EGHAS6789B",
        "aadhaar_no": "5678 9012 3456",
        "mobile": "+91-9876012345",
        "email": "anita.sharma@email.com",
        "address1": "23 CIVIL LINES",
        "address2": "",
        "city": "Jaipur",
        "state": "Rajasthan",
        "pincode": "302006",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "GOVT",
        "industry": "Government",
        "education": "Post Graduate",
        "annual_income": 3500000,
        "experian_income": 180000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "33445566778899",
        "bank_name": "PNB",
        "ifsc": "PUNB0001234",
        "nominee_name": "Sunil Sharma",
        "nominee_relation": "Husband",
        "plan": "UW3 - Term Life Insurance",
        "product_code": "UW3",
        "sum_assured": 4500000,
        "premium": 50000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "Father",
        "sro": "<2 Hours",
        "case_type": "Fresh",
        "tsa": 4500000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS678901234",
        "name": "Vikram Singh",
        "first_name": "VIKRAM",
        "last_name": "SINGH",
        "dob": "18/09/1988",
        "age": 36,
        "gender": "Male",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "FHIVS7890C",
        "aadhaar_no": "6789 0123 4567",
        "mobile": "+91-9765432109",
        "email": "vikram.singh@email.com",
        "address1": "56 SECTOR 18",
        "address2": "",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "pincode": "201301",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "PRIVATE LTD",
        "industry": "IT/Software",
        "education": "Graduate",
        "annual_income": 3000000,
        "experian_income": 150000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "22334455667788",
        "bank_name": "Kotak Bank",
        "ifsc": "KKBK0001234",
        "nominee_name": "Priya Singh",
        "nominee_relation": "Wife",
        "plan": "E21 - Endowment",
        "product_code": "E21",
        "sum_assured": 1900000,
        "premium": 30000,
        "sourcing_type": "FR",
        "advisor_code": "R3751956",
        "holding_type": "Spouse",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 1900000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS789012345",
        "name": "Meera Nair",
        "first_name": "MEERA",
        "last_name": "NAIR",
        "dob": "30/12/1995",
        "age": 29,
        "gender": "Female",
        "marital_status": "Single",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "GIJNM8901D",
        "aadhaar_no": "7890 1234 5678",
        "mobile": "+91-9654321098",
        "email": "meera.nair@email.com",
        "address1": "89 ANNA SALAI",
        "address2": "",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pincode": "600002",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "PRIVATE LTD",
        "industry": "IT/Software",
        "education": "Post Graduate",
        "annual_income": 2500000,
        "experian_income": 120000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "11223355667788",
        "bank_name": "HDFC Bank",
        "ifsc": "HDFC0002345",
        "nominee_name": "Rajan Nair",
        "nominee_relation": "Father",
        "plan": "UW3 - Term Life Insurance",
        "product_code": "UW3",
        "sum_assured": 3000000,
        "premium": 25000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "Employee",
        "sro": "<2 Hours",
        "case_type": "Fresh",
        "tsa": 3500000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS890123456",
        "name": "Arjun Kumar",
        "first_name": "ARJUN",
        "last_name": "KUMAR",
        "dob": "25/04/1978",
        "age": 46,
        "gender": "Male",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "NRI",
        "pan_no": "HJKAK9012E",
        "aadhaar_no": "8901 2345 6789",
        "mobile": "+91-9543210987",
        "email": "arjun.kumar@email.com",
        "address1": "34 JUBILEE HILLS",
        "address2": "",
        "city": "Hyderabad",
        "state": "Telangana",
        "pincode": "500033",
        "country": "Singapore",
        "occupation": "Business",
        "organisation_type": "PRIVATE LTD",
        "industry": "Retail",
        "education": "Graduate",
        "annual_income": 15000000,
        "experian_income": 900000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "44556677889900",
        "bank_name": "Yes Bank",
        "ifsc": "YESB0001234",
        "nominee_name": "Kavitha Kumar",
        "nominee_relation": "Wife",
        "plan": "UW3 - Term Life Insurance",
        "product_code": "UW3",
        "sum_assured": 9000000,
        "premium": 100000,
        "sourcing_type": "FR",
        "advisor_code": "R2640845",
        "holding_type": "Self",
        "sro": "<2 Hours",
        "case_type": "AMR",
        "tsa": 9000000,
        "audit_flag": "",
        "status": "In Progress",
    },
    {
        "app_no": "OS901234567",
        "name": "Priya Reddy",
        "first_name": "PRIYA",
        "last_name": "REDDY",
        "dob": "08/08/1992",
        "age": 32,
        "gender": "Female",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "IKLPR0123F",
        "aadhaar_no": "9012 3456 7890",
        "mobile": "+91-9432109876",
        "email": "priya.reddy@email.com",
        "address1": "67 BANJARA HILLS",
        "address2": "",
        "city": "Hyderabad",
        "state": "Telangana",
        "pincode": "500034",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "PRIVATE LTD",
        "industry": "Healthcare",
        "education": "Post Graduate",
        "annual_income": 5000000,
        "experian_income": 250000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "66778899001122",
        "bank_name": "HDFC Bank",
        "ifsc": "HDFC0003456",
        "nominee_name": "Sai Reddy",
        "nominee_relation": "Husband",
        "plan": "T74 - Term Plan",
        "product_code": "T74",
        "sum_assured": 5000000,
        "premium": 68000,
        "sourcing_type": "FR",
        "advisor_code": "R1530734",
        "holding_type": "FR",
        "sro": "<2 Hours",
        "case_type": "Fresh",
        "tsa": 5000000,
        "audit_flag": "",
        "status": "Pending",
    },
    {
        "app_no": "OS012345678",
        "name": "Suresh Menon",
        "first_name": "SURESH",
        "last_name": "MENON",
        "dob": "12/01/1970",
        "age": 54,
        "gender": "Male",
        "marital_status": "Married",
        "nationality": "Indian",
        "resident_status": "Resident",
        "pan_no": "JLMSM1234G",
        "aadhaar_no": "0123 4567 8901",
        "mobile": "+91-9321098765",
        "email": "suresh.menon@email.com",
        "address1": "11 MARINE DRIVE",
        "address2": "",
        "city": "Kochi",
        "state": "Kerala",
        "pincode": "682001",
        "country": "India",
        "occupation": "Salaried",
        "organisation_type": "GOVT",
        "industry": "Government",
        "education": "Post Graduate",
        "annual_income": 9000000,
        "experian_income": 450000,
        "politically_exposed": "No",
        "high_risk": "No",
        "bank_account": "77889900112233",
        "bank_name": "SBI",
        "ifsc": "SBIN0002345",
        "nominee_name": "Latha Menon",
        "nominee_relation": "Wife",
        "plan": "T74 - Term Plan",
        "product_code": "T74",
        "sum_assured": 10500000,
        "premium": 18000,
        "sourcing_type": "FR",
        "advisor_code": "R3751956",
        "holding_type": "Employee",
        "sro": "<2 Hours",
        "case_type": "Fresh",
        "tsa": 10500000,
        "audit_flag": "",
        "status": "Pending",
    },
]


def _seed_demo_data():
    """Insert seed cases only if the cases table is empty."""
    with get_db() as conn:
        count = conn.execute("SELECT COUNT(*) FROM cases").fetchone()[0]
        if count > 0:
            return  # Already seeded

        cols = [
            "app_no",
            "name",
            "first_name",
            "last_name",
            "dob",
            "age",
            "gender",
            "marital_status",
            "nationality",
            "resident_status",
            "pan_no",
            "aadhaar_no",
            "mobile",
            "email",
            "address1",
            "address2",
            "city",
            "state",
            "pincode",
            "country",
            "occupation",
            "organisation_type",
            "industry",
            "education",
            "annual_income",
            "experian_income",
            "politically_exposed",
            "high_risk",
            "bank_account",
            "bank_name",
            "ifsc",
            "nominee_name",
            "nominee_relation",
            "plan",
            "product_code",
            "sum_assured",
            "premium",
            "sourcing_type",
            "advisor_code",
            "holding_type",
            "sro",
            "case_type",
            "tsa",
            "audit_flag",
            "status",
        ]
        placeholders = ", ".join("?" for _ in cols)
        col_list = ", ".join(cols)
        sql = f"INSERT INTO cases ({col_list}) VALUES ({placeholders})"

        for case in _SEED_CASES:
            conn.execute(sql, [case.get(c) for c in cols])


def init_db():
    """Create tables and seed with demo data if empty."""
    _ensure_data_dir()
    with get_db() as conn:
        conn.executescript(DDL)

    _seed_demo_data()
