DEFAULT_STATE = {
    "application_no": "OS121345678",
    "current_card": 1,
    "overall_status": "In Progress",
    "fup_count": 2,
    "cards": {
        "card1": {
            "title": "Case Details",
            "status": "In Progress",
            "completed": False,
            "fields": {
                "application_no": "",
                "ca_ics_no": "",
                "case_type": "",
                "sourcing_channel": "",
                "proposed_status": "",
                "gender_la": "",
                "branch_location": "",
            },
        },
        "card2": {
            "title": "Audit 5 & KYC Checks",
            "status": "Pending",
            "completed": False,
            "sections_completed": 0,
            "total_sections": 6,
            "fup_raised": True,
            "sections": {
                "nationality": {
                    "title": "Nationality / Resident Status",
                    "completed": False,
                    "fields": {"declared_residence_iuw": ""},
                },
                "pan_validation": {
                    "title": "PAN / PAL Validation",
                    "fup_raised": True,
                    "completed": False,
                    "fields": {
                        "doc_type_uploaded": "Physical Pan",
                        "pan_copy_uploaded": None,
                        "pan_copy_clear": None,
                        "dob_matches_iuw": None,
                        "pan_number_entered": "",
                    },
                },
                "aadhaar_validation": {
                    "title": "Aadhaar Validation",
                    "completed": False,
                    "fields": {
                        "aadhaar_copy_uploaded": None,
                        "aadhaar_copy_clear": None,
                        "aadhaar_name_matches": None,
                        "aadhaar_dob_matches": None,
                        "aadhaar_number_entered": "",
                    },
                },
                "address_proof": {
                    "title": "Address Proof Validation",
                    "completed": False,
                    "fields": {
                        "address_doc_uploaded": None,
                        "address_doc_clear": None,
                        "address_matches_iuw": None,
                    },
                },
                "photo_validation": {
                    "title": "Photo Validation",
                    "completed": False,
                    "fields": {
                        "photo_uploaded": None,
                        "photo_clear": None,
                        "face_matches_id": None,
                    },
                },
                "bank_validation": {
                    "title": "Bank Account Validation",
                    "completed": False,
                    "fields": {
                        "bank_statement_uploaded": None,
                        "account_no_matches": None,
                        "name_on_statement_matches": None,
                        "account_number_entered": "",
                        "ifsc_entered": "",
                    },
                },
            },
        },
        "card3": {
            "title": "Audit 6 - Financial",
            "status": "Pending",
            "completed": False,
            "sections": {
                "occupation": {
                    "title": "Occupation & Industry",
                    "completed": False,
                    "fields": {
                        "occupation": "",
                        "industry_type": "",
                        "is_hazardous": None,
                    },
                },
                "income": {
                    "title": "Minimum Income Requirement",
                    "status": "Validated",
                    "completed": True,
                    "auto_validated": True,
                    "message": "No minimum income requirement for the selected occupation and plan combination.",
                    "fields": {"minimum_balance": ""},
                },
                "education": {
                    "title": "Education Validation",
                    "completed": False,
                    "fields": {"education_level": ""},
                },
                "nominee": {
                    "title": "Nominee Validation",
                    "completed": False,
                    "fields": {"nominee_details_added": None},
                },
            },
        },
    },
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

FIELD_MAP = {
    "pan_copy_uploaded": [
        "cards",
        "card2",
        "sections",
        "pan_validation",
        "fields",
        "pan_copy_uploaded",
    ],
    "pan_copy_clear": [
        "cards",
        "card2",
        "sections",
        "pan_validation",
        "fields",
        "pan_copy_clear",
    ],
    "dob_matches_iuw": [
        "cards",
        "card2",
        "sections",
        "pan_validation",
        "fields",
        "dob_matches_iuw",
    ],
    "aadhaar_copy_uploaded": [
        "cards",
        "card2",
        "sections",
        "aadhaar_validation",
        "fields",
        "aadhaar_copy_uploaded",
    ],
    "aadhaar_copy_clear": [
        "cards",
        "card2",
        "sections",
        "aadhaar_validation",
        "fields",
        "aadhaar_copy_clear",
    ],
    "aadhaar_name_matches": [
        "cards",
        "card2",
        "sections",
        "aadhaar_validation",
        "fields",
        "aadhaar_name_matches",
    ],
    "aadhaar_dob_matches": [
        "cards",
        "card2",
        "sections",
        "aadhaar_validation",
        "fields",
        "aadhaar_dob_matches",
    ],
    "address_doc_uploaded": [
        "cards",
        "card2",
        "sections",
        "address_proof",
        "fields",
        "address_doc_uploaded",
    ],
    "address_doc_clear": [
        "cards",
        "card2",
        "sections",
        "address_proof",
        "fields",
        "address_doc_clear",
    ],
    "address_matches_iuw": [
        "cards",
        "card2",
        "sections",
        "address_proof",
        "fields",
        "address_matches_iuw",
    ],
    "photo_uploaded": [
        "cards",
        "card2",
        "sections",
        "photo_validation",
        "fields",
        "photo_uploaded",
    ],
    "photo_clear": [
        "cards",
        "card2",
        "sections",
        "photo_validation",
        "fields",
        "photo_clear",
    ],
    "face_matches_id": [
        "cards",
        "card2",
        "sections",
        "photo_validation",
        "fields",
        "face_matches_id",
    ],
    "bank_statement_uploaded": [
        "cards",
        "card2",
        "sections",
        "bank_validation",
        "fields",
        "bank_statement_uploaded",
    ],
    "account_no_matches": [
        "cards",
        "card2",
        "sections",
        "bank_validation",
        "fields",
        "account_no_matches",
    ],
    "name_on_statement_matches": [
        "cards",
        "card2",
        "sections",
        "bank_validation",
        "fields",
        "name_on_statement_matches",
    ],
    "is_hazardous": [
        "cards",
        "card3",
        "sections",
        "occupation",
        "fields",
        "is_hazardous",
    ],
    "nominee_details_added": [
        "cards",
        "card3",
        "sections",
        "nominee",
        "fields",
        "nominee_details_added",
    ],
}

TEXT_FIELD_MAP = {
    "pan_number_entered": [
        "cards",
        "card2",
        "sections",
        "pan_validation",
        "fields",
        "pan_number_entered",
    ],
    "aadhaar_number_entered": [
        "cards",
        "card2",
        "sections",
        "aadhaar_validation",
        "fields",
        "aadhaar_number_entered",
    ],
    "account_number_entered": [
        "cards",
        "card2",
        "sections",
        "bank_validation",
        "fields",
        "account_number_entered",
    ],
    "ifsc_entered": [
        "cards",
        "card2",
        "sections",
        "bank_validation",
        "fields",
        "ifsc_entered",
    ],
    "declared_residence_iuw": [
        "cards",
        "card2",
        "sections",
        "nationality",
        "fields",
        "declared_residence_iuw",
    ],
    "occupation": ["cards", "card3", "sections", "occupation", "fields", "occupation"],
    "industry_type": [
        "cards",
        "card3",
        "sections",
        "occupation",
        "fields",
        "industry_type",
    ],
    "education_level": [
        "cards",
        "card3",
        "sections",
        "education",
        "fields",
        "education_level",
    ],
    "application_no": ["cards", "card1", "fields", "application_no"],
    "case_type": ["cards", "card1", "fields", "case_type"],
    "gender_la": ["cards", "card1", "fields", "gender_la"],
    "branch_location": ["cards", "card1", "fields", "branch_location"],
    "minimum_balance": ["cards", "card3", "sections", "income", "fields", "minimum_balance"],
}
